version: 0.2

phases:
  install:
    commands:
      - echo "Install phase - nothing required for now"

  build:
    commands:
      - echo "Build phase - skipping zip, letting CodeBuild package everything"

artifacts:
  files:
    - '**/*'
