version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "<-- RUNTIME EXECUTION -->"
      - echo "Installing pylint..."
      - pip install pylint

  build:
    commands:
      - echo "pre build stage completed"
      - echo "Running pylint for code analysis..."
      - echo "PyLint Started"
      - pylint **/*.py > pylint_report.txt || true
      - echo "pre build stage completed - PyLint Completed!!"
      - echo "Build stage completed!"

artifacts:
  files:
    - '**/*'
    - pylint_report.txt
