version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing pylint..."
      - pip install pylint

  build:
    commands:
      - echo "Running pylint for code analysis..."
      - pylint **/*.py > pylint_report.txt || true

artifacts:
  files:
    - '**/*'
    - pylint_report.txt
