version: 0.2

phases:
  install:
    commands:
      - echo "Preparing build environment..."

  build:
    commands:
      - echo "Zipping app contents for Elastic Beanstalk..."
      - zip -r app.zip * .[^.]* -x "app.zip"  # Avoid recursive zip

artifacts:
  files:
    - app.zip
