version: 0.2

phases:
  install:
    commands:
      - echo "Installing any required packages..."

  build:
    commands:
      - echo "Zipping all root-level files for Elastic Beanstalk..."
      - zip -r app.zip . -x "app.zip" "*.git*" "*__pycache__*" "*.DS_Store"

artifacts:
  files:
    - app.zip
